<?php
if (!$p) $p = $prefix;

$sql = "DROP TABLE IF EXISTS ".$p."countries";
$dba->exec( $sql );

$sql = "CREATE TABLE 
        ".$p."countries
        (
          name            VARCHAR(200),
          short_code      CHAR(2),
          long_code       CHAR(3),
          country_nr      VARCHAR(20)
        )";
$dba->exec( $sql );
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('AFGHANISTAN','AF','AFG','004')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ALBANIA','AL','ALB','008')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ALGERIA','DZ','DZA','012')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('AMERICAN SAMOA','AS','ASM','016')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ANDORRA','AD','AND','020')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ANGOLA','AO','AGO','024')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ANGUILLA','AI','AIA','660')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ANTARCTICA','AQ','ATA','010')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ANTIGUA AND BARBUDA','AG','ATG','028')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ARGENTINA','AR','ARG','032')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ARMENIA','AM','ARM','051')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ARUBA','AW','ABW','533')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('AUSTRALIA','AU','AUS','036')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('AUSTRIA','AT','AUT','040')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('AZERBAIJAN','AZ','AZE','031')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BAHAMAS','BS','BHS','044')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BAHRAIN','BH','BHR','048')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BANGLADESH','BD','BGD','050')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BARBADOS','BB','BRB','052')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BELARUS','BY','BLR','112')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BELGIUM','BE','BEL','056')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BELIZE','BZ','BLZ','084')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BENIN','BJ','BEN','204')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BERMUDA','BM','BMU','060')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BHUTAN','BT','BTN','064')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BOLIVIA','BO','BOL','068')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BOSNIA AND HERZEGOWINA','BA','BIH','070')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BOTSWANA','BW','BWA','072')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BOUVET ISLAND','BV','BVT','074')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BRAZIL','BR','BRA','076')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BRITISH INDIAN OCEAN TERRITORY','IO','IOT','086')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BRUNEI DARUSSALAM','BN','BRN','096')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BULGARIA','BG','BGR','100')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BURKINA FASO','BF','BFA','854')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('BURUNDI','BI','BDI','108')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CAMBODIA','KH','KHM','116')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CAMEROON','CM','CMR','120')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CANADA','CA','CAN','124')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CAPE VERDE','CV','CPV','132')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CAYMAN ISLANDS','KY','CYM','136')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CENTRAL AFRICAN REPUBLIC','CF','CAF','140')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CHAD','TD','TCD','148')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CHILE','CL','CHL','152')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CHINA','CN','CHN','156')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CHRISTMAS ISLAND','CX','CXR','162')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('COCOS (KEELING) ISLANDS','CC','CCK','166')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('COLOMBIA','CO','COL','170')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('COMOROS','KM','COM','174')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CONGO, Democratic Republic of (was Zaire)','CD','COD','180')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CONGO, People\'s Republic of','CG','COG','178')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('COOK ISLANDS','CK','COK','184')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('COSTA RICA','CR','CRI','188')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('COTE D\'IVOIRE','CI','CIV','384')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CROATIA (local name: Hrvatska)','HR','HRV','191')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CUBA','CU','CUB','192')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CYPRUS','CY','CYP','196')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('CZECH REPUBLIC','CZ','CZE','203')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('DENMARK','DK','DNK','208')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('DJIBOUTI','DJ','DJI','262')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('DOMINICA','DM','DMA','212')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('DOMINICAN REPUBLIC','DO','DOM','214')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('EAST TIMOR','TL','TLS','626')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ECUADOR','EC','ECU','218')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('EGYPT','EG','EGY','818')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('EL SALVADOR','SV','SLV','222')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('EQUATORIAL GUINEA','GQ','GNQ','226')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ERITREA','ER','ERI','232')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ESTONIA','EE','EST','233')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ETHIOPIA','ET','ETH','231')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FALKLAND ISLANDS (MALVINAS)','FK','FLK','238')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FAROE ISLANDS','FO','FRO','234')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FIJI','FJ','FJI','242')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FINLAND','FI','FIN','246')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FRANCE','FR','FRA','250')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FRANCE, METROPOLITAN','FX','FXX','249')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FRENCH GUIANA','GF','GUF','254')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FRENCH POLYNESIA','PF','PYF','258')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('FRENCH SOUTHERN TERRITORIES','TF','ATF','260')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GABON','GA','GAB','266')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GAMBIA','GM','GMB','270')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GEORGIA','GE','GEO','268')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GERMANY','DE','DEU','276')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GHANA','GH','GHA','288')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GIBRALTAR','GI','GIB','292')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GREECE','GR','GRC','300')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GREENLAND','GL','GRL','304')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GRENADA','GD','GRD','308')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GUADELOUPE','GP','GLP','312')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GUAM','GU','GUM','316')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GUATEMALA','GT','GTM','320')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GUINEA','GN','GIN','324')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GUINEA-BISSAU','GW','GNB','624')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('GUYANA','GY','GUY','328')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('HAITI','HT','HTI','332')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('HEARD AND MC DONALD ISLANDS','HM','HMD','334')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('HONDURAS','HN','HND','340')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('HONG KONG','HK','HKG','344')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('HUNGARY','HU','HUN','348')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ICELAND','IS','ISL','352')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('INDIA','IN','IND','356')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('INDONESIA','ID','IDN','360')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('IRAN (ISLAMIC REPUBLIC OF)','IR','IRN','364')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('IRAQ','IQ','IRQ','368')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('IRELAND','IE','IRL','372')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ISRAEL','IL','ISR','376')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ITALY','IT','ITA','380')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('JAMAICA','JM','JAM','388')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('JAPAN','JP','JPN','392')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('JORDAN','JO','JOR','400')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('KAZAKHSTAN','KZ','KAZ','398')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('KENYA','KE','KEN','404')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('KIRIBATI','KI','KIR','296')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','KP','PRK','408')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('KOREA, REPUBLIC OF','KR','KOR','410')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('KUWAIT','KW','KWT','414')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('KYRGYZSTAN','KG','KGZ','417')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LAO PEOPLE\'S DEMOCRATIC REPUBLIC','LA','LAO','418')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LATVIA','LV','LVA','428')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LEBANON','LB','LBN','422')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LESOTHO','LS','LSO','426')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LIBERIA','LR','LBR','430')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LIBYAN ARAB JAMAHIRIYA','LY','LBY','434')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LIECHTENSTEIN','LI','LIE','438')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LITHUANIA','LT','LTU','440')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('LUXEMBOURG','LU','LUX','442')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MACAU','MO','MAC','446')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','MK','MKD','807')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MADAGASCAR','MG','MDG','450')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MALAWI','MW','MWI','454')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MALAYSIA','MY','MYS','458')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MALDIVES','MV','MDV','462')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MALI','ML','MLI','466')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MALTA','MT','MLT','470')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MARSHALL ISLANDS','MH','MHL','584')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MARTINIQUE','MQ','MTQ','474')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MAURITANIA','MR','MRT','478')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MAURITIUS','MU','MUS','480')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MAYOTTE','YT','MYT','175')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MEXICO','MX','MEX','484')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MICRONESIA, FEDERATED STATES OF','FM','FSM','583')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MOLDOVA, REPUBLIC OF','MD','MDA','498')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MONACO','MC','MCO','492')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MONGOLIA','MN','MNG','496')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MONTSERRAT','MS','MSR','500')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MOROCCO','MA','MAR','504')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MOZAMBIQUE','MZ','MOZ','508')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('MYANMAR','MM','MMR','104')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NAMIBIA','NA','NAM','516')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NAURU','NR','NRU','520')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NEPAL','NP','NPL','524')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NETHERLANDS','NL','NLD','528')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NETHERLANDS ANTILLES','AN','ANT','530')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NEW CALEDONIA','NC','NCL','540')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NEW ZEALAND','NZ','NZL','554')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NICARAGUA','NI','NIC','558')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NIGER','NE','NER','562')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NIGERIA','NG','NGA','566')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NIUE','NU','NIU','570')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NORFOLK ISLAND','NF','NFK','574')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NORTHERN MARIANA ISLANDS','MP','MNP','580')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('NORWAY','NO','NOR','578')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('OMAN','OM','OMN','512')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PAKISTAN','PK','PAK','586')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PALAU','PW','PLW','585')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PALESTINIAN TERRITORY, Occupied','PS','PSE','275')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PANAMA','PA','PAN','591')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PAPUA NEW GUINEA','PG','PNG','598')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PARAGUAY','PY','PRY','600')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PERU','PE','PER','604')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PHILIPPINES','PH','PHL','608')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PITCAIRN','PN','PCN','612')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('POLAND','PL','POL','616')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PORTUGAL','PT','PRT','620')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('PUERTO RICO','PR','PRI','630')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('QATAR','QA','QAT','634')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('REUNION','RE','REU','638')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ROMANIA','RO','ROU','642')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('RUSSIAN FEDERATION','RU','RUS','643')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('RWANDA','RW','RWA','646')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SAINT KITTS AND NEVIS','KN','KNA','659')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SAINT LUCIA','LC','LCA','662')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SAINT VINCENT AND THE GRENADINES','VC','VCT','670')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SAMOA','WS','WSM','882')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SAN MARINO','SM','SMR','674')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SAO TOME AND PRINCIPE','ST','STP','678')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SAUDI ARABIA','SA','SAU','682')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SENEGAL','SN','SEN','686')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SEYCHELLES','SC','SYC','690')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SIERRA LEONE','SL','SLE','694')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SINGAPORE','SG','SGP','702')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SLOVAKIA (Slovak Republic)','SK','SVK','703')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SLOVENIA','SI','SVN','705')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SOLOMON ISLANDS','SB','SLB','090')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SOMALIA','SO','SOM','706')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SOUTH AFRICA','ZA','ZAF','710')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','GS','SGS','239')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SPAIN','ES','ESP','724')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SRI LANKA','LK','LKA','144')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ST. HELENA','SH','SHN','654')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ST. PIERRE AND MIQUELON','PM','SPM','666')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SUDAN','SD','SDN','736')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SURINAME','SR','SUR','740')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SVALBARD AND JAN MAYEN ISLANDS','SJ','SJM','744')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SWAZILAND','SZ','SWZ','748')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SWEDEN','SE','SWE','752')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SWITZERLAND','CH','CHE','756')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('SYRIAN ARAB REPUBLIC','SY','SYR','760')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TAIWAN','TW','TWN','158')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TAJIKISTAN','TJ','TJK','762')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TANZANIA, UNITED REPUBLIC OF','TZ','TZA','834')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('THAILAND','TH','THA','764')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TOGO','TG','TGO','768')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TOKELAU','TK','TKL','772')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TONGA','TO','TON','776')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TRINIDAD AND TOBAGO','TT','TTO','780')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TUNISIA','TN','TUN','788')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TURKEY','TR','TUR','792')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TURKMENISTAN','TM','TKM','795')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TURKS AND CAICOS ISLANDS','TC','TCA','796')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('TUVALU','TV','TUV','798')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('UGANDA','UG','UGA','800')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('UKRAINE','UA','UKR','804')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('UNITED ARAB EMIRATES','AE','ARE','784')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('UNITED KINGDOM','GB','GBR','826')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('UNITED STATES','US','USA','840')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('UNITED STATES MINOR OUTLYING ISLANDS','UM','UMI','581')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('URUGUAY','UY','URY','858')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('UZBEKISTAN','UZ','UZB','860')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('VANUATU','VU','VUT','548')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('VATICAN CITY STATE (HOLY SEE)','VA','VAT','336')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('VENEZUELA','VE','VEN','862')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('VIET NAM','VN','VNM','704')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('VIRGIN ISLANDS (BRITISH)','VG','VGB','092')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('VIRGIN ISLANDS (U.S.)','VI','VIR','850')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('WALLIS AND FUTUNA ISLANDS','WF','WLF','876')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('WESTERN SAHARA','EH','ESH','732')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('YEMEN','YE','YEM','887')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('YUGOSLAVIA','YU','YUG','891')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ZAMBIA','ZM','ZMB','894')");
$dba->exec("INSERT INTO ".$p."countries( name,short_code,long_code,country_nr) VALUES('ZIMBABWE','ZW','ZWE','716')");
?>
